version: '3.8'
services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    command: npm run dev
    ports:
      - "5000:5000"   # API
      - "2525:2525"   # SMTP
      - "8080:8080"   # WebSocket
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/disposable-email
    depends_on:
      - mongodb

volumes:
  mongo-data: